version: '3.9'

services:
  db-postgresql:
    image: postgres:15.2-alpine3.17
    container_name: db_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-bd
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
  
  nats:
    image: "nats-streaming:0.9.2"
    container_name: cqrs_nats
    restart: always
  
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    container_name: cqrs_elasticsearch
    environment:
      - "discover.type=single-node"
  
  feed:
    build: "."
    container_name: cqrs_feed_service
    command: "feed-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      NATS_ADDRESS: "nats:4222"

# docker compose up -d